### PR TITLE
Solutions refactor

### PR DESCRIPTION
**Pull request by skkr**
This PR is related to #92 

**To do:** 

- [ ] Use real content in quotes.
- [ ] Add links to buttons.
- [ ] Determine which images we will use.

----

**Screen capture of current state**

image

### CODE REVIEW

**Comment by skkr** [comment]
@menschikov please let me know what content to use

**Comment by menschikov** [comment]
@skkr use real content from website, make sure all content stored in JSONs

**Comment by menschikov** [comment]
@skkr it's same as #92 can you please remove unnecessary one?

**Comment by skkr** [comment]
@menschikov replaced the content we don't have with lorem ipsum.
Images and links are still pending.

**Comment by MatiasOS** [comment]
Closed in favor of #133

**Pull request closed without merging**
