### PR TITLE
refactor suppliers and sellers page, moved Solutions to Commons and u…

### PR DESCRIPTION
**Pull request by menschikov**
build proper structure (header, app-content, footer) for:
-main page
- sellers
- suppliers

Moved SubscribeForUpdates and ReadyToUse into each component to be inside app-content

Moved Solutions from Suppliers to Commons and added solution for OTA to use on sellers page. Used "variant" prop to identify what solution to show.

changed top element class .add-content to id #app-content. added div-tag instead of blank tags
@skkr did it as you reccomended but now we got blank line on top and bottom of page, please fix styles asap.
image
image

fixed team bio animation

### CODE REVIEW

**Comment by skkr** [comment]
@menschikov add this CSS `#app-content {padding: 0;}` or the class `.p-0` to `#app-content`

**Comment by skkr** [comment]
**TO DO**

- [ ] Remove padding from `#app-content` (my prev comment)
- [ ] Use `<article>` to wrap related content and `<section>` to wrap sections content inside articles

Is ok to do something like 

```
   article.app-section
   article
       section.app-section
       section.app-section
```
- [ ] Team section has wrong classes
- [ ] Remove class `.mb-md-4` from `.col-md-4` in team and advisors sections
- [ ] Avoid two consecutive white sections. Use `.bg-light` (or `border-bottom` only if gray bg looks bad)

**Comment by skkr** [comment]
We shouldn't have two consecutive sections with same background, so this is incorrect. Recommend to display the info in a different way.

image

**Comment by menschikov** [comment]
> We shouldn't have two consecutive sections with same background, so this is incorrect. Recommend to display the info in a different way.
> 
> image

see #194

**Comment by MatiasOS** [comment]
Changes from @skkr will be done in next iteration.

**Pull request merged**
